name: pipedream-dispatch

# Controls when the action will run. Triggers the workflow on push request, or repository dispatch
on:
  repository_dispatch:
    types: [Postman_Test]
jobs:
  build:
    name: Run psirt.py
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          ref: # branch
            master
      - name: execute py script # run file
        run: |
          python psirt.py